#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


function bumpThresholdCoverage {
    local coverageBumperOutput=$(npx jest-it-up --dry-run)
    local canWeUpdateCoverage=$(echo "${coverageBumperOutput}" | grep "improved code coverage");

    if [[ -n "${canWeUpdateCoverage}" ]]; then 
        echo
        npx jest-it-up \
            | grep -v "record the changes" \
            | grep -v "improved code coverage";
   
        echo "Your changes have improved code coverage. Nice work! ❤️"

        echo 
        git add "jest.config.js";
        git commit -m "chore: bump coverage threashold" --no-verify;    
        echo "Automatically persisted in git history🤖"
    fi
}

if [[ $(git diff --stat) != '' ]]; then
    echo "I see that working directory is dirty so, I will abort futher actions 😞"
    echo 
    exit 127;
fi

npm test
bumpThresholdCoverage



