#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


function shouldIncreaseCoverage {
    local coverageBumperOutput=$(npx jest-it-up --dry-run)
    local canWeUpdateCoverage=$(echo "${coverageBumperOutput}" | grep "improved code coverage");

    if [[ -n "${canWeUpdateCoverage}" ]]; then 
        return 0
    fi

    return 128
}

function bumpCoverage {
        echo
        npx jest-it-up \
            | grep -v "record the changes" \
            | grep -v "improved code coverage";

        echo 
        git add "jest.config.js";
        git commit -m "chore: bump coverage threashold" --no-verify;    
        echo
   
        echo "Your changes have improved code coverage. Nice work! ❤️"
}

if [[ $(git diff --stat) != '' ]]; then
    echo "I see that working directory is dirty so, I will abort futher actions 😞"
    echo 
    # exit 127;
fi

npm test

if shouldIncreaseCoverage; then
    bumpCoverage
fi



